### ISSUE TITLE
Reg-Ex for Capture One changed. Again

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/foigus-recipes#67]
PR incoming once I've tested, but the current CaptureOne.download.recipe recipe, fails with a curl 22 error.

```
URLDownloader
{'Input': {'filename': 'CaptureOne.dmg',
           'url': 'https://downloads.phaseone.com/5059f2ea-b489-4f19-8e68-3b359e11d00a/International/CaptureOne21.Mac.14.0.1.7.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 191, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://downloads.phaseone.com/5059f2ea-b489-4f19-8e68-3b359e11d00a/International/CaptureOne21.Mac.14.0.1.7.dmg', '--fail', '--output', '/Users/darren/Library/AutoPkg/Cache/com.github.foigus.download.CaptureOne/downloads/tmpsh9z5efc', '--header', 'If-None-Match: "a458f3d813cdb2b360b48989cbfc45d9:1602067304.852036"', '--header', 'If-Modified-Since: Wed, 07 Oct 2020 11:59:10 GMT']' returned non-zero exit status 22.
```

Looks like it's literally a revert of your commit here - https://github.com/autopkg/foigus-recipes/commit/157ffaf3ac574338a4ec4ffb8d4458d5fcacd79d#diff-361bd14c80c9065a8657bd5426a6271b9554a9d6fa168d4c46a65445ad12ecd1

I'll finish testing and get a PR in once I can confirm it's good.

**Comment by foigus** [comment]
PR accepted--closing.
